# Generated by Django 4.1.3 on 2022-12-01 18:26

import django.core.validators
from django.db import migrations, models
import fragmantica.core.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('image', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
            ],
            bases=(fragmantica.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
