# Generated by Django 4.1.3 on 2022-12-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='image',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='award',
            name='description',
        ),
    ]
