# Generated by Django 4.1.3 on 2022-12-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_rename_image_award_logo_remove_award_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='logo',
        ),
    ]
