# Generated by Django 4.1.3 on 2022-12-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_remove_award_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='logo',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
    ]
