# Generated by Django 4.1.3 on 2022-11-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
