# Generated by Django 4.1.3 on 2022-11-30 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0003_designer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='since',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2022)]),
            preserve_default=False,
        ),
    ]
