# Generated by Django 4.1.3 on 2022-11-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0005_alter_designer_since'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designer',
            old_name='Photo',
            new_name='photo',
        ),
    ]
