# Generated by Django 4.1.3 on 2022-12-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0008_designer_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='award',
        ),
    ]
