# Generated by Django 4.1.3 on 2022-12-05 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0014_alter_perfume_award'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_alter_perfumecomment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumePossesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possesion', models.CharField(choices=[('have_it', 'I have it'), ('had_it', 'I had it'), ('want_it', 'I want it')], max_length=7)),
                ('perfume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='perfumes.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
