# Generated by Django 4.1.3 on 2022-12-05 22:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0014_alter_perfume_award'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_perfumepossesion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerfumePossesion',
            new_name='PerfumePossession',
        ),
        migrations.RenameField(
            model_name='perfumepossession',
            old_name='possesion',
            new_name='possession',
        ),
    ]
