# Generated by Django 4.1.3 on 2022-11-25 16:03

import django.core.validators
from django.db import migrations, models
import fragmantica.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_fraguser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraguser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), fragmantica.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='fraguser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), fragmantica.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='fraguser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), fragmantica.core.validators.validate_only_letters]),
        ),
    ]
