# Generated by Django 4.1.3 on 2022-11-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0010_perfume_note'),
        ('accounts', '0003_alter_fraguser_first_name_alter_fraguser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraguser',
            name='perfume',
            field=models.ManyToManyField(blank=True, null=True, to='perfumes.perfume'),
        ),
    ]
