# Generated by Django 4.1.3 on 2022-11-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0010_perfume_note'),
        ('accounts', '0004_fraguser_perfume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraguser',
            name='perfume',
            field=models.ManyToManyField(to='perfumes.perfume'),
        ),
    ]
