# Generated by Django 4.1.3 on 2022-12-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_fraguser_perfume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
