# Generated by Django 4.1.3 on 2022-12-14 22:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_fraguser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraguser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fraguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
