# Generated by Django 4.1.3 on 2022-11-30 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_alter_perfume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(max_length=2022, unique=True, validators=[django.core.validators.MinLengthValidator(1960)]),
        ),
    ]
