# Generated by Django 4.1.3 on 2022-11-30 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0004_alter_perfume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
