# Generated by Django 4.1.3 on 2022-11-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_designer_slug'),
        ('perfumes', '0005_alter_perfume_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='designer',
            field=models.ManyToManyField(to='designers.designer'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
