# Generated by Django 4.1.3 on 2022-11-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_designer_slug'),
        ('perfumes', '0006_perfume_designer_perfume_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='designer',
        ),
        migrations.AddField(
            model_name='perfume',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='designers.designer'),
            preserve_default=False,
        ),
    ]
