# Generated by Django 4.1.3 on 2022-11-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0007_remove_perfume_designer_perfume_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='personal_photo',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
