# Generated by Django 4.1.3 on 2022-11-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0008_perfume_personal_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='personal_photo',
            new_name='image',
        ),
    ]
