# Generated by Django 4.1.3 on 2022-11-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('perfumes', '0009_rename_personal_photo_perfume_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='note',
            field=models.ManyToManyField(to='notes.note'),
        ),
    ]
