# Generated by Django 4.1.3 on 2022-12-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_award_logo'),
        ('perfumes', '0010_perfume_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='award',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='awards.award'),
            preserve_default=False,
        ),
    ]
