# Generated by Django 4.1.3 on 2022-12-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0014_alter_perfume_award'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='year',
            new_name='year_created',
        ),
    ]
